update file_managed set filename='Joanna Kennedy Formal photo colour.jpg' where fid = 566;
update file_managed set filename='Rebecca Sparkes.jpg' where fid = 570;
update file_managed set filename='Martin_pic.JPG' where fid = 572;
update file_managed set filename='Owen_pic.jpg' where fid = 573;
update file_managed set filename='Sandra pic (2).JPG' where fid = 574;
update file_managed set filename='Liz Morrow.JPG' where fid = 575;
update file_managed set filename='Matt pic.jpg' where fid = 576;
update file_managed set filename='Jane Whaley_pic.JPG' where fid = 577;
update file_managed set filename='Sarah Mann.JPG' where fid = 578;
update file_managed set filename='Alison Taggart pic.JPG' where fid = 579;
update file_managed set filename='Maria pic (2).JPG' where fid = 580;
update file_managed set filename='Robert.jpg' where fid = 581;
update file_managed set filename='ElizabethNeville.jpg' where fid = 582;
update file_managed set filename='IMG_4506-med.jpg' where fid = 583;
update file_managed set filename='JamesStewart.jpg' where fid = 584;
update file_managed set filename='John Gieve.jpg' where fid = 585;
update file_managed set filename='Lord Waldegrave_pic.jpg' where fid = 586;
update file_managed set filename='Lynne Berry.jpg' where fid = 587;
update file_managed set filename='Malcom Evans Cropped.jpg' where fid = 588;
update file_managed set filename='Prof Dame Julia King 1.jpg' where fid = 589;
update file_managed set filename='RalphWaller.jpg' where fid = 590;
update file_managed set filename='Salley Vickers.jpg' where fid = 591;
update file_managed set filename='Sally Davies.jpg' where fid = 592;
update file_managed set filename='SimonPearce_pic.jpg' where fid = 593;
update file_managed set filename='Adelina Gavrila.jpg' where fid = 596;
update file_managed set filename='Cathy Jamieson.JPG' where fid = 597;
update file_managed set filename='Chris Dixon.JPG' where fid = 598;
update file_managed set filename='Florence Hazrat photo.jpg' where fid = 599;
update file_managed set filename='Laura Castells Navarro photo smaller.jpg' where fid = 600;
update file_managed set filename='Laura Schuhmacher Photo New.jpg' where fid = 601;
update file_managed set filename='Navjot Sangwan photo.jpg' where fid = 602;
update file_managed set filename='Neil Sadler.jpg' where fid = 603;
update file_managed set filename='Rebecca Black photo.JPG' where fid = 604;
update file_managed set filename='Sam Fowles Photo.jpg' where fid = 605;
update file_managed set filename='map.png' where fid = 611;
update file_managed set filename='lake.jpg' where fid = 614;
update file_managed set filename='Wedding & Celebrations.jpg' where fid = 615;
update file_managed set filename='Lecture Attendees.jpg' where fid = 617;
update file_managed set filename='Services.jpg' where fid = 618;
update file_managed set filename='Grooms House.jpg' where fid = 619;
update file_managed set filename='Large Twin.jpg' where fid = 621;
update file_managed set filename='Cumberland Lodge Garden.jpg' where fid = 625;
update file_managed set filename='Cumberland Lodge Garden_0.jpg' where fid = 626;
update file_managed set filename='Denning.jpg' where fid = 637;
update file_managed set filename='Flitcroft.jpg' where fid = 638;
update file_managed set filename='Grooms-House.jpg' where fid = 639;
update file_managed set filename='american-bridge.jpg' where fid = 640;
update file_managed set filename='Janet-Atherton-Tuscan-Landscape.jpg' where fid = 642;
update file_managed set filename='runnymede-logo.jpg' where fid = 648;
update file_managed set filename='Queens-Belfast-Logo.jpg' where fid = 649;
update file_managed set filename='Tom-Kirkwood.jpg' where fid = 651;
update file_managed set filename='LSE.jpg' where fid = 652;
update file_managed set filename='Alasdair Pinkerton.jpg' where fid = 655;
update file_managed set filename='Alasdair Pinkerton_0.jpg' where fid = 656;
update file_managed set filename='rhu-london.jpg' where fid = 657;
update file_managed set filename='rad-logo.png' where fid = 659;
update file_managed set filename='Royal Academy of Dance_0.png' where fid = 660;
update file_managed set filename='Jane Whaley_pic.jpg' where fid = 741;
update file_managed set filename='Claire Agius.jpg' where fid = 742;
update file_managed set filename='Lorna Hardy.jpg' where fid = 743;
update file_managed set filename='HRH_Queen.jpg' where fid = 744;
update file_managed set filename='Houses of Parliament.jpg' where fid = 823;
update file_managed set filename='Christmas Dinner Smaller.jpg' where fid = 824;
update file_managed set filename='Cumberland Lodge Student Christmas Group Photograph.jpg' where fid = 825;
update file_managed set filename='Divided Brain Conference Image Small.jpg' where fid = 827;
update file_managed set filename='Iain McGilchrist Landscape Image.jpg' where fid = 832;
update file_managed set filename='Iain McGilchrist Confernece Image.jpg' where fid = 833;
update file_managed set filename='Economy and Social Justice.jpg' where fid = 868;
update file_managed set filename='Childrens health logo.jpg' where fid = 869;
update file_managed set filename='Police Tape Image 210x170.jpg' where fid = 870;
update file_managed set filename='Bill Knight Image.jpg' where fid = 872;
update file_managed set filename='Man and Water Bottles Image 210x130.jpg' where fid = 873;
update file_managed set filename='Simon Howard Presentation Front Cover.jpg' where fid = 877;
update file_managed set filename='Heem Shukla Presentation Front Cover.jpg' where fid = 879;
update file_managed set filename='Heem Shukla Presentation Front Cover_0.jpg' where fid = 880;
update file_managed set filename='Sally McManus Presentation Front Cover.jpg' where fid = 882;
update file_managed set filename='KBR Logo Low Res.jpg' where fid = 889;
update file_managed set filename='Police Mutual Logo.JPG' where fid = 892;
update file_managed set filename='IMG_5570.jpg' where fid = 893;
update file_managed set filename='Sortbroget_dansk_malkerace.jpg' where fid = 895;
update file_managed set filename='Thinking Faith Image_0.jpg' where fid = 902;
update file_managed set filename='london-947381_640.jpg' where fid = 920;
update file_managed set filename='Logo.png' where fid = 921;
update file_managed set filename='Inspiration.jpg' where fid = 924;
update file_managed set filename='James Clerk Maxwell_caricature_colour.jpg' where fid = 926;
update file_managed set filename='Internet.png' where fid = 929;
update file_managed set filename='Faerie Queene Image.jpg' where fid = 931;
update file_managed set filename='Religion and Secularisation.jpg' where fid = 933;
update file_managed set filename='Religion and the News.jpg' where fid = 935;
update file_managed set filename='Religion and the News Paper.jpg' where fid = 939;
update file_managed set filename='Religious Education.jpg' where fid = 940;
update file_managed set filename='LAtiva.jpg' where fid = 942;
update file_managed set filename='A boy jumps enlarged.jpg' where fid = 944;
update file_managed set filename='Beyond the Campus.jpg' where fid = 946;
update file_managed set filename='Book.jpg' where fid = 949;
update file_managed set filename='1304505299RabindranathTagore.jpg' where fid = 951;
update file_managed set filename='Bayeux image 600x180.jpg' where fid = 954;
update file_managed set filename='Bayeux 210x130.jpg' where fid = 955;
update file_managed set filename='Crisis in University.jpg' where fid = 956;
update file_managed set filename='Books.jpg' where fid = 958;
update file_managed set filename='OXford Univesity.jpg' where fid = 960;
update file_managed set filename='IBM logo small.jpg' where fid = 968;
update file_managed set filename='Dr Tim Brain Cover.jpg' where fid = 987;
update file_managed set filename='Divided Brain Conference Image Small_0.jpg' where fid = 997;
update file_managed set filename='Population and Ethics Final Logo.jpg' where fid = 1004;
update file_managed set filename='Garden Path.jpg' where fid = 1306;
update file_managed set filename='Surveillance.jpg' where fid = 1307;
update file_managed set filename='Drugs and Harm 285 x 140.jpg' where fid = 1309;
update file_managed set filename='Drugs.jpg' where fid = 1311;
update file_managed set filename='Fear.jpg' where fid = 1314;
update file_managed set filename='Target.png' where fid = 1315;
update file_managed set filename='Prison.jpg' where fid = 1317;
update file_managed set filename='Domestic Violence.png' where fid = 1319;
update file_managed set filename='NEighbourhood.jpg' where fid = 1321;
update file_managed set filename='People Are Police.jpg' where fid = 1326;
update file_managed set filename='Prison_0.jpg' where fid = 1327;
update file_managed set filename='Lock.jpg' where fid = 1328;
update file_managed set filename='Police Bike.jpg' where fid = 1330;
update file_managed set filename='Handcuffs White Background 210x130.jpg' where fid = 1332;
update file_managed set filename='Handcuffs-Black.jpg' where fid = 1334;
update file_managed set filename='Police parade.jpg' where fid = 1336;
update file_managed set filename='Cop March.jpg' where fid = 1337;
update file_managed set filename='death flowers.jpg' where fid = 1339;
update file_managed set filename='Bioethics icon.jpg' where fid = 1343;
update file_managed set filename='dna.jpg' where fid = 1345;
update file_managed set filename='HIV image 210.jpg' where fid = 1347;
update file_managed set filename='Stethoscope cropped.jpg' where fid = 1349;
update file_managed set filename='Conference image.jpg' where fid = 1351;
update file_managed set filename='hands-981400_1920.jpg' where fid = 1353;
update file_managed set filename='liverpool-1078854_1920.jpg' where fid = 1354;
update file_managed set filename='cc social determinants logo.jpg' where fid = 1355;
update file_managed set filename='family silhouette composite.png' where fid = 1356;
update file_managed set filename='T Helper Cell.png' where fid = 1358;
update file_managed set filename='Rural Population.jpg' where fid = 1360;
update file_managed set filename='Antarctic.jpg' where fid = 1362;
update file_managed set filename='Johannesburg.jpg' where fid = 1364;
update file_managed set filename='Climate logo 140x285.jpg' where fid = 1366;
update file_managed set filename='Climate Change.jpg' where fid = 1367;
update file_managed set filename='Arts Funding.jpg' where fid = 1369;
update file_managed set filename='Sunset.jpg' where fid = 1371;
update file_managed set filename='Gender.png' where fid = 1373;
update file_managed set filename='Squeezed Britain.jpg' where fid = 1375;
update file_managed set filename='Minority Rights.jpg' where fid = 1377;
update file_managed set filename='Why Languages Matter.png' where fid = 1379;
update file_managed set filename='European Regional Politics.png' where fid = 1381;
update file_managed set filename='Corporate Social Responsibility.jpg' where fid = 1383;
update file_managed set filename='Translation.png' where fid = 1385;
update file_managed set filename='Free Speech and the Internet.jpg' where fid = 1388;
update file_managed set filename='Future of the Third Sector.jpg' where fid = 1390;
update file_managed set filename='The New Politics of Belonging.jpg' where fid = 1392;
update file_managed set filename='Swing.jpg' where fid = 1394;
update file_managed set filename='Children\'s Rights.jpg' where fid = 1396;
update file_managed set filename='teaching-661748_1920.jpg' where fid = 1398;
update file_managed set filename='Workplace Organisation.jpg' where fid = 1399;
update file_managed set filename='clock-70189_1920.jpg' where fid = 1400;
update file_managed set filename='reconnoiter-60779_1920.jpg' where fid = 1401;
update file_managed set filename='heart-care-1040248_1280.png' where fid = 1402;
update file_managed set filename='niki-de-saint-phalle-67684_1920.jpg' where fid = 1403;
update file_managed set filename='baby-390941_1920.jpg' where fid = 1404;
update file_managed set filename='children-516342_1920.jpg' where fid = 1405;
update file_managed set filename='conference-room-768441_1920.jpg' where fid = 1406;
update file_managed set filename='achievement-18134_1920.jpg' where fid = 1407;
update file_managed set filename='balance-865817_1920.jpg' where fid = 1408;
update file_managed set filename='continents-695162_1920.jpg' where fid = 1409;
update file_managed set filename='africa-657774_1280.jpg' where fid = 1411;
update file_managed set filename='circle-1270671_1280.png' where fid = 1412;
update file_managed set filename='architecture-2671_1920.jpg' where fid = 1413;
update file_managed set filename='st-pauls-cathedral-652629_1920.jpg' where fid = 1414;
update file_managed set filename='three-1325105_1280.png' where fid = 1415;
update file_managed set filename='neighborhood-802074_1920.jpg' where fid = 1416;
update file_managed set filename='Ethnic Inequalities Conference Logo Small File Size.jpg' where fid = 1417;
update file_managed set filename='CODE large.jpg' where fid = 1419;
update file_managed set filename='Code Logo Small.jpg' where fid = 1420;
update file_managed set filename='Tufyal Choudhury Cover.jpg' where fid = 1444;
update file_managed set filename='Mental Health Logo with white background.jpg' where fid = 1445;
update file_managed set filename='Cumberland Logo December.png' where fid = 1446;
update file_managed set filename='Centre for the Study of Existential Risk.png' where fid = 1468;
update file_managed set filename='Royal Economic Society.png' where fid = 1471;
update file_managed set filename='Violence Against Women Conference Logo Large.jpg' where fid = 1473;
update file_managed set filename='IMG_9776.jpg' where fid = 1477;
update file_managed set filename='Architecture.jpg' where fid = 1478;
update file_managed set filename='The Role of the Arts.jpg' where fid = 1482;
update file_managed set filename='The Sopa Opera.jpg' where fid = 1483;
update file_managed set filename='What Are Museums For.jpg' where fid = 1484;
update file_managed set filename='Alcohol.jpg' where fid = 1485;
update file_managed set filename='Drink and Disorder.jpg' where fid = 1486;
update file_managed set filename='Marriage.jpg' where fid = 1487;
update file_managed set filename='Ageing.jpg' where fid = 1488;
update file_managed set filename='Stehoscope.png' where fid = 1489;
update file_managed set filename='NHS Logo.png' where fid = 1490;
update file_managed set filename='Waiting Room.jpg' where fid = 1491;
update file_managed set filename='NHS Collaboration.jpg' where fid = 1492;
update file_managed set filename='NHS Standards of Care.jpg' where fid = 1493;
update file_managed set filename='Christians and Muslims.jpg' where fid = 1494;
update file_managed set filename='Islam the British Experience.jpg' where fid = 1496;
update file_managed set filename='Religion and Society.jpg' where fid = 1497;
update file_managed set filename='Reawakening.jpg' where fid = 1498;
update file_managed set filename='World Christianity.jpg' where fid = 1499;
update file_managed set filename='Being British.jpg' where fid = 1500;
update file_managed set filename='Making Cities Work.jpg' where fid = 1501;
update file_managed set filename='Policing the Environment.jpg' where fid = 1502;
update file_managed set filename='The Environment Debate.jpg' where fid = 1503;
update file_managed set filename='New Politics of Economy.jpg' where fid = 1504;
update file_managed set filename='Urban Growth.jpg' where fid = 1505;
update file_managed set filename='Iman Azzi Photo.jpg' where fid = 1506;
update file_managed set filename='Harriet Hoffler Photo.jpg' where fid = 1507;
update file_managed set filename='Rebecca Love Photo.jpg' where fid = 1508;
update file_managed set filename='Nick Thompson Photo.jpg' where fid = 1509;
update file_managed set filename='Liisa Tuhkanen Photo.png' where fid = 1510;
update file_managed set filename='Michael Veale Photo.jpg' where fid = 1511;
update file_managed set filename='Travis Elborough Book Cover.png' where fid = 1514;
update file_managed set filename='Windsor Festival Logo Gold Smaller.jpg' where fid = 1515;
update file_managed set filename='Adrian Tinniswood Book Cover Smaller.jpg' where fid = 1516;
update file_managed set filename='Windsor Festival Logo Gold Smaller_0.jpg' where fid = 1517;
update file_managed set filename='Adrian Tinniswood Book Cover Smaller_0.jpg' where fid = 1518;
update file_managed set filename='Madeleine Bunting Book Cover Smaller.jpg' where fid = 1519;
update file_managed set filename='Windsor Festival Logo Gold Smaller_1.jpg' where fid = 1520;
update file_managed set filename='Sarah Gristwood Book Cover.jpg' where fid = 1521;
update file_managed set filename='Windsor Festival Logo Gold Smaller_3.jpg' where fid = 1523;
update file_managed set filename='Professor Sir Partha Dasgupta Official.jpg' where fid = 1524;
update file_managed set filename='Crime and Disorder.jpg' where fid = 1533;
update file_managed set filename='Criminal Justice and the Media.jpg' where fid = 1534;
update file_managed set filename='Drugs Where Next.jpg' where fid = 1535;
update file_managed set filename='Homeless.jpg' where fid = 1536;
update file_managed set filename='Policing and Safety.jpg' where fid = 1537;
update file_managed set filename='Prisons in the Community.jpg' where fid = 1538;
update file_managed set filename='Responding to Domestic Violence.jpg' where fid = 1539;
update file_managed set filename='Victims\' Rights.jpg' where fid = 1540;
update file_managed set filename='Youth Offenders.jpg' where fid = 1541;
update file_managed set filename='Cumberland Lodge Police Conference Image 2016 Small_0.jpg' where fid = 1542;
update file_managed set filename='Post School Learning.jpg' where fid = 1543;
update file_managed set filename='British Muslims and State Education.jpg' where fid = 1544;
update file_managed set filename='Celebrating Racial Diversity.jpg' where fid = 1545;
update file_managed set filename='Commonwealth Higher Education_0.jpg' where fid = 1547;
update file_managed set filename='Overseas Students.jpg' where fid = 1548;
update file_managed set filename='Values in Commonwealth Education.jpg' where fid = 1549;
update file_managed set filename='What Are Universities For.jpg' where fid = 1550;
update file_managed set filename='An Asian Agenda for British Public Policy.jpg' where fid = 1551;
update file_managed set filename='Britain' where fid = 1552;
update file_managed set filename='Crime Reduction.png' where fid = 1553;
update file_managed set filename='Serving the People.jpg' where fid = 1554;
update file_managed set filename='The End of Britain.png' where fid = 1555;
update file_managed set filename='Democratic Society.jpg' where fid = 1556;
update file_managed set filename='British Society for Population Studies.jpg' where fid = 1559;
update file_managed set filename='Year of the Family.jpg' where fid = 1563;
update file_managed set filename='Children and Young People at Risk.jpg' where fid = 1564;
update file_managed set filename='Turning the Tider.png' where fid = 1565;
update file_managed set filename='Troublesome Adolescent.jpg' where fid = 1566;
update file_managed set filename='Sir Mark Walport Front Cover.jpg' where fid = 1567;
update file_managed set filename='Sir Mark Walport Front Cover Square_0.jpg' where fid = 1569;
update file_managed set filename='BFG dream bottles at Cumberland Lodge (3) web use.jpg' where fid = 1572;
update file_managed set filename='BFG dream bottles at Cumberland Lodge (3) web use_0.jpg' where fid = 1573;
update file_managed set filename='BFG dream bottles at Cumberland Lodge (3) web use_1.jpg' where fid = 1574;
update file_managed set filename='Society for Applied Philosophy.gif' where fid = 1575;
update file_managed set filename='Jaunt - by Penny Warden from \'Strictly Movement\' exhibition.jpg' where fid = 1576;
update file_managed set filename='Jaunt - by Penny Warden from \'Strictly Movement\' exhibition.jpg' where fid = 1577;
update file_managed set filename='Jaunt - by Penny Warden from \'Strictly Movement\' exhibition_0.jpg' where fid = 1581;
update file_managed set filename='Jaunt - by Penny Warden from \'Strictly Movement\' exhibition_0.jpg' where fid = 1582;
update file_managed set filename='Fervour.jpg' where fid = 1584;
update file_managed set filename='Hula.jpg' where fid = 1586;
update file_managed set filename='Enticement.jpg' where fid = 1588;
update file_managed set filename='Ethnic Inequalities conference.jpg' where fid = 1600;
update file_managed set filename='Commonwealth Scholarships Logo.png' where fid = 1601;
update file_managed set filename='Rebecca Birks - web.jpg' where fid = 1602;
update file_managed set filename='Rachel Smillie' where fid = 1603;
update file_managed set filename='Emma Albery' where fid = 1604;
update file_managed set filename='Cumberland Lodge Lo_Res-7.jpg' where fid = 1618;
update file_managed set filename='Shami Chakrabarti (Oct 2016).jpg' where fid = 1619;
update file_managed set filename='Sara Thornton.jpg' where fid = 1621;
update file_managed set filename='ed newell preferred 12.07.16_0.jpg' where fid = 1645;
update file_managed set filename='Population and Ethics Final Logo_1.jpg' where fid = 1656;
update file_managed set filename='Amy Buller Scan - Small.jpg' where fid = 1667;
update file_managed set filename='The God Slot speakers Nov 16.JPG' where fid = 1668;
update file_managed set filename='g' where fid = 1669;
update file_managed set filename='Christmas card low res.jpg' where fid = 1670;
update file_managed set filename='Thought for the Day.jpg' where fid = 1672;
update file_managed set filename='IMGP0201.jpg' where fid = 1673;
update file_managed set filename='Kat Eghdamian - Research Associate.JPG' where fid = 1680;
update file_managed set filename='4star Self Catering VisitEngland small 72dpi.jpg' where fid = 1689;
update file_managed set filename='Discourses of Empire & Commonwealth book cover.jpg' where fid = 1691;
update file_managed set filename='Ethnic Inequalities Conference Logo Small File Size_0.jpg' where fid = 1694;
update file_managed set filename='Life Beyond the PhD Image.jpg' where fid = 1695;
update file_managed set filename='Population ethics - 2nd image.jpg' where fid = 1696;
update file_managed set filename='Ethnic inequality - 2nd image.jpg' where fid = 1697;
update file_managed set filename='Ethnic inequality - 3rd image.jpg' where fid = 1698;
update file_managed set filename='cl-friends-pos-cmyk small 72dpi.jpg' where fid = 1700;
update file_managed set filename='Nicola Sharp-Jeffs - Research Associate.jpg' where fid = 1701;
update file_managed set filename='Violence Against Women Conference Logo Large_0.jpg' where fid = 1702;
update file_managed set filename='CL 70th anniversary full colour jpeg logo - low res.jpeg' where fid = 1705;
update file_managed set filename='CL 70th anniversary logo on light artichoke background 2 rectangular.png' where fid = 1716;
update file_managed set filename='CL 70th anniversary logo on light artichoke background 2 rectangular_0.png' where fid = 1717;
update file_managed set filename='CL 70th anniversary logo on light artichoke background 2 rectangular 2.png' where fid = 1718;
update file_managed set filename='0Grant.jpg' where fid = 1719;
update file_managed set filename='Flowers small 72dpi.jpg' where fid = 1723;
update file_managed set filename='Amy Buller cropped.jpg' where fid = 1724;
update file_managed set filename='SCAN0898_001 crop.jpg' where fid = 1725;
update file_managed set filename='INDI.jpg' where fid = 1730;
update file_managed set filename='Mahrukh Bashir 1.jpg' where fid = 1732;
update file_managed set filename='Lucy Temple - JUBILEE.jpg' where fid = 1737;
update file_managed set filename='Lucy Temple - INDI.jpg' where fid = 1739;
update file_managed set filename='The Cross-Cultural Legacy with chapter by Alastair Niven - Dec 16_0.jpg' where fid = 1748;
update file_managed set filename='PC080179.jpg' where fid = 1749;
update file_managed set filename='PC080244.jpg' where fid = 1750;
update file_managed set filename='PC080235.jpg' where fid = 1751;
update file_managed set filename='PC080233.jpg' where fid = 1752;
update file_managed set filename='PC080235_0.jpg' where fid = 1753;
update file_managed set filename='PC080210.jpg' where fid = 1754;
update file_managed set filename='PC080192.jpg' where fid = 1755;
update file_managed set filename='PC080230.jpg' where fid = 1756;
update file_managed set filename='PC080202.jpg' where fid = 1757;
update file_managed set filename='PC080217.jpg' where fid = 1758;
update file_managed set filename='PC080197.jpg' where fid = 1759;
update file_managed set filename='PB300158 edit.jpg' where fid = 1760;
update file_managed set filename='PB290087.jpg' where fid = 1762;
update file_managed set filename='PB300139 edit.jpg' where fid = 1765;
update file_managed set filename='PB300153 edit.jpg' where fid = 1766;
update file_managed set filename='PB300142 edit.jpg' where fid = 1767;
update file_managed set filename='PB300133 edit.jpg' where fid = 1768;
update file_managed set filename='PB300116 edit 2.jpg' where fid = 1770;
update file_managed set filename='PB300124 edit 3.jpg' where fid = 1771;
update file_managed set filename='PB300125 edit_0.jpg' where fid = 1772;
update file_managed set filename='PB300109_0.jpg' where fid = 1773;
update file_managed set filename='Handbook image.jpg' where fid = 1775;
update file_managed set filename='cumberland_lodge_conference_day-5.jpg' where fid = 1776;
update file_managed set filename='161217_CLXmas_179.jpg' where fid = 1777;
update file_managed set filename='P1060515.jpg' where fid = 1778;
update file_managed set filename='Cumberland_Lodge_Rooms_2_(24_of_74) smaller.jpg' where fid = 1790;
update file_managed set filename='Rowan Williams 72dpi.jpg' where fid = 1792;
update file_managed set filename='161216_CLXmas__0022.jpg' where fid = 1796;
update file_managed set filename='161217_CLXmas_347.jpg' where fid = 1797;
update file_managed set filename='161217_CLXmas_215.jpg' where fid = 1798;
update file_managed set filename='Mahrukh Bashir art (square 96dpi).jpg' where fid = 1799;
update file_managed set filename='Eliminating Slavery (square).jpg' where fid = 1800;
update file_managed set filename='Martin Parsons (square 72dpi).jpg' where fid = 1801;
update file_managed set filename='Rowan Williams 72dpi.jpg' where fid = 1802;
update file_managed set filename='161216_CLXmas__0009.jpg' where fid = 1804;
update file_managed set filename='The Mews in summer (72dpi).jpg' where fid = 1806;
update file_managed set filename='Social Inequalities image (square crop 72dpi).jpg' where fid = 1808;
update file_managed set filename='DSC_0157 (72dpi).jpg' where fid = 1809;
update file_managed set filename='The Patron\'s Fund.png' where fid = 1811;
update file_managed set filename='The Patron\'s Fund square logo.jpg' where fid = 1812;
update file_managed set filename='Hannah Breeze (2) for web.jpg' where fid = 1813;
update file_managed set filename='P2030693-2.jpg' where fid = 1817;
update file_managed set filename='P2030698-2.jpg' where fid = 1818;
update file_managed set filename='Amy Buller cropped_0.jpg' where fid = 1820;
update file_managed set filename='Darkness Over Germany Original Cover (1943) wide.png' where fid = 1821;
update file_managed set filename='Amy Buller cropped 2.jpg' where fid = 1822;
update file_managed set filename='P2090830.jpg' where fid = 1823;
update file_managed set filename='Freedom of religion (square crop).jpg' where fid = 1826;
update file_managed set filename='Fine dining (square).jpg' where fid = 1832;
update file_managed set filename='St Georges Chapel' where fid = 1834;
update file_managed set filename='Violence Against Women Conference Logo Large_1.jpg' where fid = 1836;
update file_managed set filename='in the jungle new size (square crop for web).jpg' where fid = 1837;
update file_managed set filename='dancing lady (square crop).jpg' where fid = 1839;
update file_managed set filename='Buckley 06_After The Monsoon_27x20cm (square crop).jpg' where fid = 1841;
update file_managed set filename='Monsoon Leaves_by Samantha Buckley_water based pigments on Wasli paper_30x24cm (square crop).jpg' where fid = 1842;
update file_managed set filename='Charles Anson 2 (72dpi).jpg' where fid = 1851;
update file_managed set filename='Sally Dewar 2017.jpg' where fid = 1852;
update file_managed set filename='Group Photo.jpg' where fid = 1856;
update file_managed set filename='Book burning image - square crop (Shutterstock standard licence 2017).jpg' where fid = 1861;
update file_managed set filename='VAW - Image 2 (Smaller) square canvas.jpg' where fid = 1866;
update file_managed set filename='Apprentices 1-2.jpg' where fid = 1867;
update file_managed set filename='P3080885-2.jpg' where fid = 1868;
update file_managed set filename='Holy Trinity Garrison Church Windsor square crop.jpg' where fid = 1870;
update file_managed set filename='Baroness Helena Kennedy 72dpi.jpg' where fid = 1871;
update file_managed set filename='Rowan Williams 72dpi_0.jpg' where fid = 1872;
update file_managed set filename='Maiken Umbach.jpg' where fid = 1873;
update file_managed set filename='Kurt Barling.jpeg' where fid = 1874;
update file_managed set filename='Sally Dewar.jpg' where fid = 1876;
update file_managed set filename='Tariq Modood.jpg' where fid = 1879;
update file_managed set filename='Nicholas_Stern_026 for web.jpg' where fid = 1880;
update file_managed set filename='Janis Reeves Handbook Image web.jpg' where fid = 1881;
update file_managed set filename='Annual Report 2015-16 cover image.JPG' where fid = 1891;
update file_managed set filename='The Mews in summer (72dpi).jpg' where fid = 1892;
update file_managed set filename='The Arrow of History image shutterstock_67626964 (web).jpg' where fid = 1894;
update file_managed set filename='Daniel-Finkelstein (Google 1).jpg' where fid = 1895;
update file_managed set filename='CL 70th anniversary logo on light artichoke background 2 rectangular 2_0.png' where fid = 1899;
update file_managed set filename='Flowers small 72dpi.jpg' where fid = 1908;
update file_managed set filename='Cumberland_Lodge_3_(25_of_49) Library (web).jpg' where fid = 1909;
update file_managed set filename='Summer Special rate graphic (square).png' where fid = 1910;
update file_managed set filename='Summer Special rate graphic (for web).png' where fid = 1911;
update file_managed set filename='Prince\'s Trust International Leaders Programme 2017 group photo (2).jpg' where fid = 1918;
update file_managed set filename='Delegates in Conference Room  (Sub Home page slider (610x300px)).JPG' where fid = 1919;
update file_managed set filename='Julia Unwin - Speaker at Inequalities & Social Cohesion seminar 28 Mar 2017 (web).jpg' where fid = 1920;
update file_managed set filename='Front door of Lodge (web).jpg' where fid = 1921;
update file_managed set filename='Baroness Butler-Sloss.jpg' where fid = 1922;
update file_managed set filename='Baroness Butler-Sloss (2).jpg' where fid = 1923;
update file_managed set filename='Social Inequalities image (square crop 72dpi)_0.jpg' where fid = 1928;
update file_managed set filename='Theodore Zeldin photo (official' where fid = 1929;
update file_managed set filename='Jane Bailey 1-2.jpg' where fid = 1931;
update file_managed set filename='cumberland_lodge_conference_day-8_0.jpg' where fid = 1934;
update file_managed set filename='DSC_0147 web.jpg' where fid = 1937;
update file_managed set filename='cumberland-lodge-pos-rgb.jpg' where fid = 1946;
update file_managed set filename='FoRB first retreat group photo on Tapestry Hall steps' where fid = 1956;
update file_managed set filename='Sara Thornton_0.jpg' where fid = 1957;
update file_managed set filename='stargardt.jpg' where fid = 1980;
update file_managed set filename='Tamsin_Shot_10180.jpg' where fid = 1982;
update file_managed set filename='LordSkidelsky-03.jpg' where fid = 2005;
update file_managed set filename='Elizabeth Morrow photo.jpg' where fid = 2006;
update file_managed set filename='Iman Monawar.jpg' where fid = 2007;
update file_managed set filename='Aoife McLoughlin-2.jpg' where fid = 2021;
update file_managed set filename='P6010133 square crop for web.jpg' where fid = 2026;
update file_managed set filename='P6010133.jpg' where fid = 2033;
update file_managed set filename='eduction low res.jpg' where fid = 2034;
update file_managed set filename='VAW - Image 2 (Smaller).jpg' where fid = 2035;
update file_managed set filename='DSC_0099 web crop.jpg' where fid = 2051;
update file_managed set filename='conference image website_0.jpg' where fid = 2052;
update file_managed set filename='chain crop.jpg' where fid = 2057;
update file_managed set filename='chain crop_0.jpg' where fid = 2058;
update file_managed set filename='Greg Hurst' where fid = 2061;
update file_managed set filename='Ruth Scott 3 - Jan 2017 square crop.jpg' where fid = 2062;
update file_managed set filename='Cumberland_Lodge_11th_June_2017_(026_of_210) web.jpg' where fid = 2071;
update file_managed set filename='chain crop_1.jpg' where fid = 2096;
update file_managed set filename='chain-690088_1920_2.jpg' where fid = 2098;
update file_managed set filename='logo.png' where fid = 2101;
update file_managed set filename='logo_0.png' where fid = 2102;
update file_managed set filename='logo_1.png' where fid = 2103;
update file_managed set filename='logo_2.png' where fid = 2104;
update file_managed set filename='logo_3.png' where fid = 2105;
update file_managed set filename='P7160647.jpg' where fid = 2107;
update file_managed set filename='bfg 2 v2 low res.jpg' where fid = 2108;
update file_managed set filename='hands bolds.jpg' where fid = 2111;
update file_managed set filename='eduction low res_0.jpg' where fid = 2215;
update file_managed set filename='eduction low res_2.jpg' where fid = 2218;
update file_managed set filename='shutterstock_441658117.jpg' where fid = 2274;
update file_managed set filename='Small_0.jpg' where fid = 2276;
update file_managed set filename='Violence Against Women Conference Logo Landscape.jpg' where fid = 2295;
update file_managed set filename='Francesca Menichellin (small image).jpg' where fid = 2321;
update file_managed set filename='rsz_dsc_7520.jpg' where fid = 2370;
update file_managed set filename='Matt pic.jpg' where fid = 2371;
update file_managed set filename='Edit Nell rearing - Gem Hall.jpg' where fid = 2380;
update file_managed set filename='Edit Nell rearing - Gem Hall_0.jpg' where fid = 2381;
update file_managed set filename='IMGP0298cropped_0.jpg' where fid = 2414;
update file_managed set filename='191011-079cropped.jpg' where fid = 2415;
update file_managed set filename='P8161019 - Landscape (Web).jpg' where fid = 2431;
update file_managed set filename='P8161019 - Landscape (Web).jpg' where fid = 2434;
update file_managed set filename='shutterstock_441658117_1.jpg' where fid = 2472;
update file_managed set filename='1882 edward with young george christian helena etc.jpg' where fid = 2566;
update file_managed set filename='1200px-Russian_Imperial_Family_1913.jpg' where fid = 2568;
update file_managed set filename='A Generationm without Hate_11.jpg' where fid = 2579;
update file_managed set filename='Small.jpg' where fid = 2580;
update file_managed set filename='British flag eroding.jpg' where fid = 2584;
update file_managed set filename='Book covers collage.jpg' where fid = 2585;
update file_managed set filename='Windsor Festival Logo Black.jpg' where fid = 2586;
update file_managed set filename='SHAMI - Roddy Paine.jpg' where fid = 2587;
update file_managed set filename='Windsor Festival Logo Black.jpg' where fid = 2588;
update file_managed set filename='Salley Vickers_1.jpg' where fid = 2597;
update file_managed set filename='SHAMI - Roddy Paine_1.jpg' where fid = 2600;
update file_managed set filename='Windsor Festival Logo Black_4.jpg' where fid = 2601;
update file_managed set filename='Salley Vickers_3.jpg' where fid = 2603;
update file_managed set filename='Windsor Festival Logo Black_0.jpg' where fid = 2604;
update file_managed set filename='Windsor Festival Logo Black_3.jpg' where fid = 2606;
update file_managed set filename='Dennison-Matthew crop_0.jpg' where fid = 2609;
update file_managed set filename='Windsor Festival Logo Black_2.jpg' where fid = 2611;
update file_managed set filename='Pankhurst crop.jpg' where fid = 2613;
update file_managed set filename='Conference image no black line.jpg' where fid = 2629;
update file_managed set filename='Resized for Web FINAL.jpg' where fid = 2631;
update file_managed set filename='CCJ Logo jpg.jpg' where fid = 2632;
update file_managed set filename='Cumberland Lodge.jpg' where fid = 2639;
update file_managed set filename='shutterstock_441658117_2.jpg' where fid = 2658;
update file_managed set filename='Anthony-Heath-pic-2.jpg' where fid = 2688;
update file_managed set filename='Shelina Janmohamed web.jpg' where fid = 2692;
update file_managed set filename='Nasar.jpg' where fid = 2694;
update file_managed set filename='James Nazaroo photo_0.jpg' where fid = 2695;
update file_managed set filename='Patrick Vernon.jpg' where fid = 2696;
update file_managed set filename='Profile - Zamila Bunglawala (3).jpg' where fid = 2698;
update file_managed set filename='Sunder web.jpg' where fid = 2699;
update file_managed set filename='Lucinda Platt photo.jpg' where fid = 2700;
update file_managed set filename='claire alexander photo 2018.jpg' where fid = 2701;
update file_managed set filename='Anne Wafula Strike.jpg FINAL.jpg' where fid = 2703;
update file_managed set filename='Panel incl Ellena Moriarty CUP.jpg' where fid = 2706;
update file_managed set filename='Grace Davie 1.jpg' where fid = 2707;
update file_managed set filename='web banner.png' where fid = 2711;
update file_managed set filename='web banner_0.png' where fid = 2712;
update file_managed set filename='web banner 2.jpg' where fid = 2713;
update file_managed set filename='web banner_1.png' where fid = 2714;
update file_managed set filename='web banner_2.png' where fid = 2715;
update file_managed set filename='FoRB image for Keep in Touch tile_0.jpg' where fid = 2728;
update file_managed set filename='DSC_9923_edited.jpg' where fid = 2729;
update file_managed set filename='Conference image no black line_0.jpg' where fid = 2732;
update file_managed set filename='Christmas Tapestry Hall - by Sandor Pomozi (Dec 16) - low-res file.jpg' where fid = 2734;
update file_managed set filename='Conference image difficult histories .jpg' where fid = 2740;
update file_managed set filename='Conference image no black line_1.jpg' where fid = 2759;
update file_managed set filename='Police web.jpg' where fid = 2771;
update file_managed set filename='KBR Website_0.png' where fid = 2774;
update file_managed set filename='Conference image no black line_2.jpg' where fid = 2775;
update file_managed set filename='British flag eroding_0.jpg' where fid = 2778;
update file_managed set filename='Kiri.jpg' where fid = 2784;
update file_managed set filename='Working Identities.jpg' where fid = 2786;
update file_managed set filename='Conference Image Working Identities.jpg' where fid = 2787;
update file_managed set filename='Conference Image Working Identities_0.jpg' where fid = 2788;
update file_managed set filename='Sarah Churchill web.jpg' where fid = 2793;
update file_managed set filename='19th Century Lodge_reduced.jpg' where fid = 2794;
update file_managed set filename='DSC_1017.jpg' where fid = 2801;
update file_managed set filename='DwYhaDYX0AA--AV.jpg' where fid = 2802;
update file_managed set filename='IMG_0438.jpg' where fid = 2803;
update file_managed set filename='DwYhaDYX0AA--AV.jpg' where fid = 2804;
update file_managed set filename='181008_CLPostTruth_29_0.jpg' where fid = 2810;
update file_managed set filename='Pictionary LR.jpg' where fid = 2824;
update file_managed set filename='Students chatting 2018 LR.jpg' where fid = 2827;
update file_managed set filename='Crackers LR.jpg' where fid = 2829;
update file_managed set filename='Around the clock LR.jpg' where fid = 2833;
update file_managed set filename='DSC_9505_edited small.jpg' where fid = 2839;
update file_managed set filename='John Madejski.png' where fid = 2864;
update file_managed set filename='Conference image difficult histories _0.jpg' where fid = 2873;
update file_managed set filename='Working Identities_0.jpg' where fid = 2885;
update file_managed set filename='Conference Image Working Identities_1.jpg' where fid = 2886;
update file_managed set filename='Digital Inclusion Image FINAL web.jpg' where fid = 3144;

