<?php

/**
 * @file
 * Contains srn_flotsam_and_jetsam.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_help().
 */
function srn_flotsam_and_jetsam_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the srn_flotsam_and_jetsam module.
    case 'help.page.srn_flotsam_and_jetsam':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Floating oddments; collected, herded bits and pieces') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_theme().
 */
function srn_flotsam_and_jetsam_theme() {
  return [
    'srn_flotsam_and_jetsam' => [
      'render element' => 'children',
    ],
  ];
}



/**
 * Implements hook_CTYPE_update().
 */
function srn_flotsam_and_jetsam_node_update(Drupal\Core\Entity\EntityInterface $entity) {

  // Entity bundles to act on
  $bundles = ['resource'];

  if (in_array($entity->bundle(), $bundles)) {
    // get the taxo term(s) this relates to, and update their 'last resource update'
    // field to NOW, so that we can sort on this field later in a view...
    if (!empty($entity->field_project)) {
      foreach($entity->field_project->referencedEntities() as $tax_project) {
        $tax_project->set('field_last_resource_update', date('Y-m-d\TH:i:s', time()));
        $tax_project->save();
      }
    }
  }
}


/**
 * Implements hook_ENTITY_TYPE_update().
 */
//function manage_finish_date_node_update(Node $node) {
//  ManageFinishDate::update_time();
//}

#field_last_resource_update